# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bf9bb519b47d5afa77d2fb375606d213b0af279347c7505307f2f2fd387806d2f035578a2e9d26818b3564042930f4a5deac10129ba18d3d25d638a8f41a3d

test:
  secret_key_base: 105a1a99603e83ef1ef66817ff40e85f95ac9b9a123998b4796e4b6534a8e5014ff3f35d164f2a94ddfaf16f016028c35ee55178440adc6123a59717a8cee573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
